# Generated by Django 3.1.1 on 2020-10-01 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question_var', models.TextField(blank=True)),
                ('option_1', models.CharField(max_length=900)),
                ('option_2', models.CharField(max_length=900)),
                ('option_3', models.CharField(max_length=900)),
                ('option_4', models.CharField(max_length=900)),
                ('answer', models.CharField(max_length=900)),
                ('answer_no', models.IntegerField()),
            ],
        ),
    ]
